name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
      - "feature/*"
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run lint
      - run: npm run lint:fix

  cypress-run:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run runheadless